### ISSUE TITLE
Increase maximum scaffold allowance?

### ISSUE THREAD

**Issue by peterdfields** [LynchLab/MAPGD#11]
I was just wondering if it would be possible to increase maximum scaffold allowance, given I'm getting the following error:

proview.cc:222: maximum scaffold count reached. Exiting

**Comment by LynchLab** [comment]
This error message may be somewhat cryptic. What is (hopefully?) going on
is that the preview command is getting confused when combining multiple
mpileup files (mapgd proview -i foo.mpileup bar.mpileup). This can be
remedied by giving the command the header from the bam file (mapgd proview
-H bam.header -i foo.mpileup bar.mpileup). The header itself can be
generated by the samtools view -H foo.bam command.

Hope this helps. I'll rework the error message to make it more transparent.

**Comment by peterdfields** [comment]
I'm not combining mpileup files. Sorry I didn't provide the full command earlier. What I'm actually doing is:

mapgd proview -i population.mpileup >  population.pro

The population.mpileup derives from running samtools mpileup on two poolseq bam files. Do you think the suggested fix is the same in the case I'm describing?

**Comment by LynchLab** [comment]
Hmmm. The maximum number of scaffolds is 65,536 right now. It is very easy to increase this maximum, (I just need to change a line in the typdef.h file, but perhaps I can make this user set), but I'm concerned that you may have fewer than 65,536 scaffolds and some other problem is occurring. Do you actually need more scaffolds?

**Comment by LynchLab** [comment]
Is it possible that a scaffold name is repeated twice in the mpileup?

**Comment by peterdfields** [comment]
There are less then 65,536 scaffolds and I don't believe there are any repeated scaffold names. I added the header option you described above and it seems to be running fine and well past where the error occurred before.

**Comment by LynchLab** [comment]
Well, this still concerns me since I don't see why you should have needed to use the header file. I'm going to leave this open for now.

**Comment by LynchLab** [comment]
This shouldn't be a problem in the new version
