### ISSUE TITLE
missing .idx file

### ISSUE THREAD

**Issue by peterdfields** [LynchLab/MAPGD#19]
When trying to run the basic example for pooled sequence data I get the following error following calling mapgd pool:

map-file.cc:80: cannot open metapopulation.idx for reading.
Error: No such file or directory

Is there an additional indexing step (sorta like samtools index) or should this file been created by the use of mapgd proview?

**Comment by LynchLab** [comment]
It's bad documentation/programming on my part. If you create files with I/O
redirection (i.e. command > output), then you don't need any additional
files, but if you create files with the output option (i.e. command -o
output) then two files should be created, one of which ends with idx. The
one caveat is that mapgd only checks the file extension right now to figure
out whether or not it needs a separate 'idx' file. This is a dumb way to do
things, and I need to fix it. But, in the mean time you can create an idx
file with the command "sam2idx" which takes a sam formatted header and
converts it to a mapgd formatted header.

-Matt
