### ISSUE TITLE
Linkage command produces incorrect header error

### ISSUE THREAD

**Issue by dseok** [LynchLab/MAPGD#25]
Running the following command: 

`mapgd linkage -p pro -m map > population-lnk.out`

Produces the following error: 
`map-file.cc:591 attempted to open incorrect header.
@NAME:SCAFFOLDS VERSION:0.4.20  FORMAT:TEXT     CONCATENATED
GENOME
map-file.cc:595 could not initilize 6Allele
@NAME:SCAFFOLDS VERSION:0.4.20  FORMAT:TEXT     CONCATENATED`

Here are the first few lines of the pro file:
`@NAME:QUARTETS	VERSION:0.4.20	FORMAT:TEXT	INDEXED
@ID0       	ID1	REF	highcov.mpileup:1	highcov.mpileup:2
CM002977.3	1	N	0/25/0/0       	0/16/0/0
CM002977.3	2	N	26/0/0/0       	17/0/0/0`

And the first few lines of the map file:
`@NAME:SCAFFOLDS	VERSION:0.4.20	FORMAT:TEXT	CONCATENATED
@NAME          	LENGTH
CM002977.3	225584828
@END_TABLE
@NAME:GENOME	VERSION:0.4.20	FORMAT:TEXT	CONCATENATED	INDEXED
@SCFNAME    	POS	REF	MAJOR	MINOR	COVERAG	MJ_FREQ	MN_FREQ	ERROR	NULL_ER	F_STAT	MM_FREQ	Mm_FREQ	mm_FREQ	HETERO	POLY_LR	HWE_LR	GOF	EF_CHRM	IND_INC	IND_CUT	BEST_LL
CM002977.3	438	N	A	C	58	0.7500	0.2500	0.0010	0.2241	-0.0000	0.5000	0.5000	0.0000	0.5000	49.99	0.34	0.32	4.00	2	0	-3.3361
CM002977.3	554	N	T	C	56	0.7500	0.2500	0.0010	0.1964	-0.0000	0.5000	0.5000	0.0000	0.5000	33.82	0.34	-0.38	4.00	2	0	-4.6652`
(This command was only ran with two individuals and the first chromosome of a genome).

What could be going on? Thanks for all of the help!

**Comment by LynchLab** [comment]
There was a bug where the program carried too much about the name of a file and didn't pay enough attention to the information in the header line, but this was fixed (I think) sometime in version 0.4.26? You shouldn't have to re-make the pro file or the map file themselves, but you could try updating to the latest version of the program (0.4.27). Alternatively you could try renaming pro "pro.out" and map "map.out" and see if that fixes the problems. Let me know how it goes.

**Comment by dseok** [comment]
We're having some troubles with installing the latest version of the program. Here's the output upon running make test:
`(project_python-2.7.9)[dseok@node107 MAPGD-master]$ make test
Makefile:77: warning: overriding commands for target `.PHONY'
Makefile:63: warning: ignoring old commands for target `.PHONY'
make -C src
make[1]: Entering directory `/project/mplattlab/software/programs/MAPGD-master/src'
make -C mapgd_0.4
make[2]: Entering directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4'
make -C gzstream
make[3]: Entering directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4/gzstream'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4/gzstream'
make[2]: Leaving directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4'
make[1]: Leaving directory `/project/mplattlab/software/programs/MAPGD-master/src'
make -C src test
make[1]: Entering directory `/project/mplattlab/software/programs/MAPGD-master/src'
make -C mapgd_0.4
make[2]: Entering directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4'
make -C gzstream
make[3]: Entering directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4/gzstream'
make[3]: Nothing to be done for `default'.
make[3]: Leaving directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4/gzstream'
make[2]: Leaving directory `/project/mplattlab/software/programs/MAPGD-master/src/mapgd_0.4'
echo
cd test && bash test.sh
cat spitze-mpileup.txt | ../../bin/mapgd proview -H spitze-header.txt > proview.out                          ../../bin/mapgd: error while loading shared libraries: libhts.so.1: cannot open shared object file: No such file or directory
[proview] produced unexpected behavior.
make[1]: *** [test] Error 1
make[1]: Leaving directory `/project/mplattlab/software/programs/MAPGD-master/src'
make: *** [test] Error 2`

Any idea what could be going wrong here?

**Comment by LynchLab** [comment]
It looks like it isn't finding the correct version of libhts.so at run
time. To fix this you can either set your environment variable LD_LIBRARY_PATH
with a path to the object (e.g 'export
LD_LIBRARY_PATH=/nfs/users/nfs_m/ma18/src/htslib/', or re-compile mapgd w/o
hts. Right now I don't use hts for much, so if you just comment out the
line "HAVE_HTS" in your top level Make file and type 'make clean; make'
things should work.

-Matt

**Comment by dseok** [comment]
We completed updating. It looks like the linkage command runs without error, but it just produces an empty file like this:

`@NAME:SCAFFOLDS	VERSION:0.4.27-2016-12-20	FORMAT:TEXT	CONCATENATED
@NAME          	LENGTH
CM002977.3	225584828
@END_TABLE
@NAME:LINKAGE	VERSION:0.4.27-2016-12-20	FORMAT:TEXT	CONCATENATED	INDEXED
@SCFNAME	POS_X	POS_Y	DIST	BEST_D	BEST_D'	BEST_D2	BEST_R2	ADJ_BEST_D	ADJ_BEST_D'	ADJ_BEST_D2	ADJ_BEST_r2	Ni	LOGLIKE
@END_TABLE`

Is this an artefact of only using two individuals and a limited set of the genome? Or is there something else going on?

Thanks

**Comment by LynchLab** [comment]
Hmm. My guess is it is the -M setting, which is the minimum number of
individuals sequenced at a site needed to calculate LD. By default I
believe it is 10, so you may want to reduce that until you get some output.

-Matt

**Comment by dseok** [comment]
Success! Thank you so much.
