### ISSUE TITLE
./configure --prefix option ignored for make install

### ISSUE THREAD

**Issue by eburgueno** [LynchLab/MAPGD#28]
After running ./configure using the `--prefix` option, make install continues to use `/usr/local/bin`:

```
$ ./configure  --prefix=/tmp/software/MAPGD-0.5 --with-htslib=/tmp/libs/htslib-1.3.1
(...)
configure: creating ./config.status
config.status: creating Makefile
config.status: executing po-directories commands

$ make install
(...)
install -m 0755 ../../bin/mapgd /usr/local/bin
install: cannot create regular file ‘/usr/local/bin/mapgd’: Permission denied
make[2]: *** [install] Error 1
make[2]: Leaving directory `/home/appiarium/packages/MAPGD-master/src/mapgd_0.4'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/home/appiarium/packages/MAPGD-master/src'
make: *** [install] Error 2
```

I think the issue is that it's being hardcoded under `src/mapgd_<version>/Makefile`: `DESTDIR=/usr/local/bin`

**Comment by eburgueno** [comment]
Further to this issue, your `install` command is incomplete:

```
./src/mapgd_0.4/Makefile:	install -m 0755 $(TARGET) $(DESTDIR)
```

This will simply copy the binary, but it assumes that `--prefix` exists (in my ./configure above, it will copy mapgd as `/tmp/software/MAPGD-0.5`)

**Comment by LynchLab** [comment]
After reading https://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR I think you are right. I've changed target to include only the name of the binary and  changed the install command to 

install -m 0755 ../../bin/$(TARGET) $(DESTDIR)$(bindir)/$(TARGET)

Which I believe should be correct for most purposes. I'm not sure if there is any expectation of initially being able to compile the binary in a directory other than  ../../bin/
