### ISSUE TITLE
Compiler error: No rule to make target `objs/mpi_relatedness.cc', needed by `objs/mpi_relatedness.o'.  Stop.

### ISSUE THREAD

**Issue by twooldridge** [LynchLab/MAPGD#30]
Hi,
I'm trying to compile MAPGD on a compute cluster running CentOS. This is with
 - GCC 6.2.0
 - openmpi 2.0.2

After unzipping the folder, I run:
```
cd MAPGD-master
./configure
make
```
The configure step seems to complete fine, only throwing this warning:
```
configure: WARNING: no configuration information is in ../htslib
```
Then when I run `make`, it seems to be compiling fine right up until it encounters `mpi_relatedness`, throwing the following error:
```
make[2]: *** No rule to make target `objs/mpi_relatedness.cc', needed by `objs/mpi_relatedness.o'.  Stop.
```
My weak understanding, after some googling, is that the compiler is looking for `mpi_relatedness.cc` in the wrong place, but I'm unsure how to fix it. I've tried copying `mpi_relatedness.cc` to `objs`, and it seems to start compiling, only to throw a long error message preceded by:
```
objs/mpi_relatedness.cc:79:2: error: ‘sample_names’ was not declared in this scope
```

Do you have any recommendations here? Let me know if you need any more information.

Thank you,
Brock

**Comment by LynchLab** [comment]
Could you send me the Makefile (in the top level directory) and config.log?
I'm not sure what is going on.

-Matt

**Comment by twooldridge** [comment]
Sure, I've attached them here. The Makefile only has the `.txt` extension because I wasn't able to upload a file without a recognizable format. 

[config.log](https://github.com/LynchLab/MAPGD/files/1932289/config.log)
[Makefile.txt](https://github.com/LynchLab/MAPGD/files/1932300/Makefile.txt)

Thank you!

**Comment by dslater82** [comment]
I am running into the same error
```
make[2]: *** No rule to make target `objs/mpi_relatedness.cc', needed by `objs/mpi_relatedness.o'.  Stop.
```
Is there a way to disable MPI?  There is no option I see in the configure step.  In the generated Makefile, I changed HAVE_MPI=no but then when I run make I get
```
g++: error: missing argument to ‘-L’
```

**Comment by matthew-ackerman** [comment]
I think I figured this one out, and it was because it was possible to switch between different compilers for mpi and non-mpi source code. I've fixed this and haven't had any problems recently. Let me know if anyone runs into similar problems.
